[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Taras Nytiaha", email = "taras.nytiaha@gmail.com"},
]
dependencies = [
    "Django~=4.2",
    "uvicorn>=0.22.0",
]
requires-python = ">=3.11"
license = {text = "MIT"}
